"use strict";
(() => {
  const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined&&text!==null)node.textContent=text;if(cls)node.className=cls;return node;};
  const request=(action,input={})=>window.timewarp.request(action,input).catch(error=>{throw Error(error.message.replace(/^Error invoking remote method '[^']+': (?:Error: )?/,''));});
  window.timewarpMountOnboarding=host=>{
    if(host.dataset.setupMounted)return;host.dataset.setupMounted='true';
    const view=el('section',null,'tw-journey');view.setAttribute('aria-label','Set up Timewarp');host.append(view);
    const bar=el('header',null,'tw-journey-bar'),brand=el('div',null,'tw-journey-brand'),logo=el('img');logo.src='./timewarp-logo.svg';logo.alt='';brand.append(logo,el('span','Timewarp'));bar.append(brand);view.append(bar);
    const signOut=el('button','Sign out','tw-journey-link');signOut.type='button';signOut.onclick=()=>void run(async()=>{await request('signOut');location.reload()});bar.append(signOut);
    const companion=el('aside',null,'tw-companion'),mascot=el('img');mascot.src='./assets/timewarp-mascot-orbit.png';mascot.alt='Your Timewarp agent';companion.append(mascot,el('span','Your agent','tw-companion-name'));view.append(companion);
    const content=el('div',null,'tw-journey-content'),error=el('p',null,'tw-journey-error');error.setAttribute('role','alert');view.append(content,error);
    let state={},busy=false,detection=null,detecting=false,disposed=false,typing=null,poll=null,frame=null,epoch=0,planAudience='individual';
    let security=null,securityRow=null,securityLoading=false,securityPending=false,securityStarted=false,securityError=null;
    const spoken=new Set();
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const icon=name=>{const img=el('img');img.src='./onboarding-icons/'+name+'.svg';img.alt='';img.className='tw-service-icon';return img;};
    const cleanup=()=>{disposed=true;clearInterval(typing);clearTimeout(poll);cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('focus',focus);window.removeEventListener('timewarp:organization-ready',load)};
    const observer=new MutationObserver(()=>{if(!host.isConnected)cleanup()});observer.observe(document.body,{childList:true,subtree:true});
    function button(label,action,kind='primary'){const node=el('button',label,'tw-journey-button '+kind);node.type='button';node.onclick=()=>void run(action);return node;}
    async function run(action){if(busy||disposed)return;busy=true;error.textContent='';view.setAttribute('aria-busy','true');view.querySelectorAll('button,input').forEach(node=>node.disabled=true);try{await action()}catch(failure){error.textContent=failure.message||'Something went wrong. Try again.';}finally{busy=false;view.removeAttribute('aria-busy');view.querySelectorAll('button,input').forEach(node=>node.disabled=false);}}
    async function advance(action,input={}){state=await request('onboardingAction',{action,...input});render();}
    function reveal(){view.dataset.speaking='false';content.querySelectorAll('[inert]').forEach(node=>node.inert=false);const input=content.querySelector('.tw-journey-name-form input');if(input&&!busy)input.focus();}
    function speak(text,sub){const key=state.step+':'+text,animate=!reduced&&!spoken.has(key);view.dataset.speaking=String(animate);const heading=el('h1',null,'tw-journey-heading');heading.setAttribute('aria-label',text);heading.tabIndex=-1;const visible=el('span',animate?'':text);visible.setAttribute('aria-hidden','true');heading.append(visible);content.append(heading);const body=el('p',animate?'':sub,'tw-journey-subtitle');body.setAttribute('aria-label',sub||'');content.append(body);clearInterval(typing);if(!animate){queueMicrotask(reveal);return;}let position=0;const total=text.length+(sub||'').length;typing=setInterval(()=>{if(disposed){clearInterval(typing);return;}position+=2;visible.textContent=text.slice(0,Math.min(position,text.length));body.textContent=(sub||'').slice(0,Math.max(0,position-text.length));if(position>=total){clearInterval(typing);spoken.add(key);reveal();}},24);}
    function footer(back,next){if(!next)return;const row=el('footer',null,'tw-journey-footer');row.append(next);content.append(row);}
    function nameForm(label,value,action,placeholder){const form=el('form',null,'tw-journey-name-form'),input=el('input');input.type='text';input.value=value||'';input.placeholder=placeholder;input.maxLength=80;input.required=true;input.autocomplete=action==='user'?'given-name':'off';input.setAttribute('aria-label',label);const submit=button('Continue →',()=>{});submit.type='submit';submit.onclick=null;form.append(input,submit);form.onsubmit=event=>{event.preventDefault();void run(()=>advance(action,{name:input.value.trim()}))};content.append(form);}
    function theme(scheme,color){view.dataset.scheme=scheme;view.style.setProperty('--journey-accent',color);const rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255),max=Math.max(...rgb),min=Math.min(...rgb),delta=max-min;let hue=0;if(delta){hue=max===rgb[0]?((rgb[1]-rgb[2])/delta)%6:max===rgb[1]?(rgb[2]-rgb[0])/delta+2:(rgb[0]-rgb[1])/delta+4;hue*=60;}view.dataset.hue=String((hue+360)%360);}
    function render(){if(disposed)return;epoch++;clearTimeout(poll);clearInterval(typing);content.replaceChildren();error.textContent='';const step=state.step||'agent';view.dataset.step=step;theme(state.theme?.scheme||'light',state.theme?.color||'#E9D2FF');
      companion.querySelector('span').textContent=state.agentName||'Your agent';const history=el('div',null,'tw-chat-history');const replies=[state.agentName&&['agent','My agent is '+state.agentName+'.'],state.userName&&['user','Call me '+state.userName+'.'],Object.keys(state.imports||{}).length&&['knowledge','My knowledge is connected.'],state.theme&&['theme',state.theme.scheme==='dark'?'Dark mode. Make it mine.':'Light mode. Make it mine.']].filter(Boolean);const order=['agent','user','knowledge','theme','reaction','plans','finish'];for(const [stage,text]of replies.filter(([stage])=>order.indexOf(stage)<order.indexOf(step))){const prompts={agent:'What would you like to call me?',user:'What should I call you?',knowledge:'Let’s put your knowledge to work.',theme:'What theme feels like you?'};history.append(el('p',prompts[stage],'tw-past-message'),el('p',text,'tw-user-reply'));}content.append(history);
      if(step==='agent'){speak('Hey 👋','I’m your Timewarp agent. We’re going to make a great team. I can help with your work on a computer — but first, what would you like to call me?');nameForm('Agent name',state.agentName,'agent','What will you call me?');}
      else if(step==='user'){speak(state.agentName+'. That’s me!','And you? What should I call you?');nameForm('Your name',state.userName,'user','Your name');footer('agent');}
      else if(step==='knowledge'){speak('Nice to meet you, '+state.userName+'.','Let’s put your knowledge to work. Connect what you’d like me to learn from — we can always add more later.');renderKnowledge();}
      else if(step==='theme'){
        speak(Object.keys(state.imports||{}).length?'Great, I feel enlightened.':'A fresh start. I like that too.','What theme do you prefer?');
        let scheme=state.theme?.scheme||(state.appearance?.scheme==='dark'?'dark':'light'),color=state.theme?.color||'#E9D2FF',radiance=state.theme?.radiance??state.appearance?.radiance??.5;theme(scheme,color);
        const choices=el('div',null,'tw-settings-form');
        function setting(title,description,control){const row=el('div',null,'tw-settings-row'),label=el('div');label.append(el('strong',title),el('p',description));row.append(label,control);choices.append(row);}
        const schemeSelect=el('select');schemeSelect.setAttribute('aria-label','Theme');for(const mode of ['light','dark']){const option=el('option',mode==='light'?'Light':'Dark');option.value=mode;schemeSelect.append(option);}schemeSelect.value=scheme;schemeSelect.onchange=()=>{scheme=schemeSelect.value;theme(scheme,color)};setting('Theme','Use a light or dark appearance',schemeSelect);
        const editor=el('div',null,'tw-native-theme-editor'),swatch=button('',async()=>{editor.hidden=!editor.hidden;swatch.setAttribute('aria-expanded',String(!editor.hidden));},'color-trigger');swatch.setAttribute('aria-label','Customize colors');swatch.setAttribute('aria-expanded','false');const chip=el('span');chip.style.background=color;swatch.append(chip,el('span','⌄'));setting('Colors','Pick a color and radiance',swatch);editor.hidden=true;
        const canvas=el('input',null,'tw-color-canvas');canvas.type='color';canvas.value=color;canvas.setAttribute('aria-label','Theme color');canvas.oninput=()=>{color=canvas.value;paint()};const field=el('div',null,'tw-color-field'),knob=el('button',null,'tw-color-knob');knob.type='button';knob.setAttribute('aria-label','Theme color. Use arrow keys to adjust.');let px=.7,py=.5;const move=(x,y)=>{px=Math.max(0,Math.min(1,x));py=Math.max(0,Math.min(1,y));const hue=(Math.atan2(py-.5,px-.5)*180/Math.PI+360)%360,light=.73+Math.min(1,Math.hypot(px-.5,py-.5)*2)*.2;const channels=[0,8,4].map(n=>{const k=(n+hue/30)%12,a=.72*Math.min(light,1-light);return Math.round(255*(light-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0')});color='#'+channels.join('');knob.style.left=(px*100)+'%';knob.style.top=(py*100)+'%';paint()};field.onpointerdown=e=>{field.setPointerCapture(e.pointerId);const r=field.getBoundingClientRect();move((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)};field.onpointermove=e=>{if(field.hasPointerCapture(e.pointerId)){const r=field.getBoundingClientRect();move((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)}};knob.onkeydown=e=>{const directions={ArrowLeft:[-.03,0],ArrowRight:[.03,0],ArrowUp:[0,-.03],ArrowDown:[0,.03]};if(directions[e.key]){e.preventDefault();const [x,y]=directions[e.key];move(px+x,py+y)}};field.append(knob);editor.append(field);const custom=el('label','Custom color','tw-custom-hex');custom.append(canvas);editor.append(custom);
        const colors=el('div',null,'tw-journey-colors');colors.setAttribute('role','group');colors.setAttribute('aria-label','Timewarp color themes');
        const paint=()=>{theme(scheme,color);chip.style.background=color;knob.style.background=color;canvas.value=color;view.style.setProperty('--journey-radiance',String(radiance));updateWave();colors.querySelectorAll('button').forEach(node=>node.setAttribute('aria-pressed',String(node.dataset.color.toLowerCase()===color.toLowerCase())));};
        for(const preset of state.presets||[]){const node=button('',async()=>{color=preset.hex;paint()},'swatch');const sample=el('span',null,'tw-preset-swatch');sample.style.background=preset.hex;node.append(sample,el('span',preset.name,'tw-preset-name'),el('small',preset.hex));node.dataset.color=preset.hex;node.setAttribute('aria-label',preset.name);colors.append(node);}editor.append(colors);
        const radianceLabel=el('label','Radiance','tw-radiance'),range=el('input');range.type='range';range.min='0';range.max='1';range.step='.001';range.value=radiance;range.setAttribute('aria-label','Theme radiance');range.oninput=()=>{radiance=Number(range.value);paint()};const svgEl=(tag,attrs={})=>{const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value]of Object.entries(attrs))node.setAttribute(key,value);return node;};
        const wave=svgEl('svg',{viewBox:'0 -7.605 455 70',preserveAspectRatio:'xMinYMid meet','aria-hidden':'true'}),defs=svgEl('defs'),gradientId='tw-radiance-'+epoch,gradient=svgEl('linearGradient',{id:gradientId}),stops=[0,0,0,100].map((offset,i)=>svgEl('stop',{offset:offset+'%', 'stop-color':'currentColor','stop-opacity':i<2?'.58':'.16'}));gradient.append(...stops);defs.append(gradient);const curve=svgEl('path',{d:"M 51.373 27.395 C 60.14 -8.503 68.906 -8.503 77.671 27.395 C 86.438 63.293 95.205 63.293 103.971 27.395 C 112.738 -8.503 121.504 -8.503 130.271 27.395 C 139.037 63.293 147.803 63.293 156.57 27.395 C 165.335 -8.503 174.101 -8.503 182.868 27.395 C 191.634 63.293 200.4 63.293 209.167 27.395 C 217.933 -8.503 226.7 -8.503 235.467 27.395 C 244.233 63.293 252.999 63.293 261.765 27.395 C 270.531 -8.503 279.297 -8.503 288.064 27.395 C 296.83 63.293 305.596 63.293 314.363 27.395 C 323.13 -8.503 331.896 -8.503 340.662 27.395 M 314.438 27.395 C 323.204 -8.503 331.97 -8.503 340.737 27.395 C 349.503 63.293 358.27 63.293 367.037 27.395",fill:'none',stroke:'url(#'+gradientId+')','stroke-linecap':'round','stroke-linejoin':'round','stroke-width':'8','vector-effect':'non-scaling-stroke'});wave.append(defs,curve);const waveControl=el('span',null,'tw-wave-control');waveControl.append(wave,range);radianceLabel.append(waveControl);function updateWave(){stops[1].setAttribute('offset',Math.max(0,radiance*100-1)+'%');stops[2].setAttribute('offset',Math.min(100,radiance*100+1)+'%');curve.setAttribute('transform','translate(0 27.3) scale(1 '+(.28+radiance*.72)+') translate(0 -27.3)');range.style.setProperty('--theme-thumb-height',(32+radiance*12)+'px');range.style.setProperty('--theme-thumb-width',(8+radiance*12)+'px');}editor.append(radianceLabel);choices.append(editor);content.append(choices);paint();footer(null,button('This feels like me →',()=>advance('theme',{scheme,color,radiance})));
      }else if(step==='reaction'){speak('Not my favourite color, but it works. 😉','Your workspace, your rules.');footer('theme',button('Let’s pick a plan →',async()=>{await request('onboardingAction',{action:'plans'});state=await request('onboardingState');render()}));}
      else if(step==='plans'){speak('How do you want me to work?','Choose the pace that fits you.');renderPlans();}
      else if(step==='finish'){speak('Let’s get to work.','You and '+state.agentName+'. A little less busywork, a lot more possibility.');const label=state.selectedPlan==='free'?'Your Free plan is ready. Connect Codex in Billing or add credits when you’re ready to run your first task.':'Your plan is confirmed and your workspace is ready.';content.append(el('p',label,'tw-journey-subtitle'));footer('plans',button('Enter my workspace →',async()=>{await request('onboardingAction',{action:'complete'});location.hash='#/';location.reload()}));}
      for(const child of content.children){if(!child.matches('.tw-chat-history,.tw-journey-heading,.tw-journey-subtitle')){child.classList.add('tw-chat-response');child.inert=view.dataset.speaking==='true';}}
      if(state.step!=='agent')requestAnimationFrame(()=>content.querySelector('.tw-journey-heading')?.scrollIntoView({block:'start',behavior:reduced?'instant':'smooth'}));
    }
    // Windows: Codex's command sandbox, set up here as the previous app did,
    // without administrator rights. The row updates in place as setup runs.
    function renderSecurity(){
      if(security&&!security.supported)return;
      securityRow=el('section',null,'tw-journey-security');securityRow.hidden=true;content.append(securityRow);paintSecurity();
      if(!security&&!securityLoading){securityLoading=true;request('sandboxStatus').then(data=>{security=data},()=>{security={supported:false}}).finally(()=>{securityLoading=false;paintSecurity()});}
    }
    function paintSecurity(){
      const row=securityRow;if(disposed||!row?.isConnected)return;
      if(!security?.supported){row.hidden=true;return;}
      row.hidden=false;
      const failed=securityPending?null:securityError||(security.status==='unavailable'?security.error||'Windows security setup is unavailable.':null),ready=!securityPending&&!failed&&security.status==='ready';
      const text=el('div',null,'tw-journey-security-text'),detail=el('p',failed||(ready?'Ready to work safely in the folders you choose':'Setting up isolated access to your work'));if(failed)detail.className='failed';text.append(el('h2','Protect work with Windows security'),detail);
      let trailing;
      if(ready)trailing=el('span','✓ Ready','tw-journey-button quiet');
      else if(failed){trailing=el('button','Retry','tw-journey-button secondary');trailing.type='button';trailing.onclick=()=>setUpSecurity(true);}
      else{trailing=el('span',null,'tw-journey-spinner');trailing.setAttribute('role','status');trailing.setAttribute('aria-label','Setting up Windows security');}
      row.replaceChildren(icon('shield'),text,trailing);
      if(!securityStarted&&['notConfigured','updateRequired'].includes(security.status)){securityStarted=true;setUpSecurity(false);}
    }
    function setUpSecurity(retry){securityPending=true;securityError=null;paintSecurity();request('sandboxSetup',{retry}).then(data=>{security=data},failure=>{securityError=failure.message||'Windows security setup failed.'}).finally(()=>{securityPending=false;paintSecurity()});}
    function renderKnowledge(){
      renderSecurity();
      const list=el('div',null,'tw-journey-import-grid');content.append(list);const note=el('p','Selected browser sessions and saved logins are copied into Timewarp on this device. Memory and skills stay local.','tw-journey-fineprint');content.append(note);
      footer('user',button(Object.keys(state.imports||{}).length?'Continue →':'Skip for now →',()=>advance('knowledge-done')));
      if(!detection){list.append(el('p','Looking for profiles and local knowledge…','tw-journey-subtitle'));if(!detecting){detecting=true;const version=epoch;request('onboardingDetect').then(data=>{detection=data;if(!disposed&&version===epoch)render()}).catch(failure=>{if(version===epoch){list.replaceChildren(el('p',failure.message),button('Try again',async()=>{detection=await request('onboardingDetect');render()},'secondary'));}}).finally(()=>detecting=false);}return;}
      for(const group of [{id:'browser',name:'Browser profiles',mark:'↗',description:'Use your Chrome and Edge profiles in Timewarp’s browser.'},{id:'codex',name:'ChatGPT / Codex',mark:'✳',description:'Local instructions, memories and skills.'},{id:'claude',name:'Claude',mark:'✦',description:'Bring your local Claude knowledge.'},{id:'cursor',name:'Cursor',mark:'⌘',description:'Rules and skills from your computer.'}]){
        const card=el('section',null,'tw-journey-import-card'),head=el('div',null,'tw-journey-card-head');head.append(icon(group.id==='browser'?'browser':group.id==='codex'?'chatgpt':group.id),el('h2',group.name));card.append(head,el('p',group.description,'tw-journey-card-copy'));
        const items=group.id==='browser'?detection.profiles:(detection.items||[]).filter(item=>group.id==='codex'?item.source==='codex-chatgpt':group.id==='claude'?item.source.startsWith('claude'):item.source==='cursor');
        const selections=el('div',null,'tw-journey-selections');
        for(const item of items){const names=group.id==='browser'?[item.name]:item.names;for(const name of names){const row=el('label'),check=el('input');check.type='checkbox';check.checked=true;check.dataset.id=item.id;check.dataset.name=name;const label=group.id==='browser'?item.name:name;row.append(check);if(group.id==='browser'){const browser=item.browser.toLowerCase();row.append(icon(['edge','firefox','safari','brave','arc','opera','vivaldi','chromium','chrome'].find(name=>browser.includes(name))||'browser'));}row.append(el('span',label));selections.append(row);}}
        if(items.length){card.append(selections);const count=items.reduce((sum,item)=>sum+(item.names?.length||1),0),connected=items.every(item=>state.imports?.[item.id]);card.append(el('p',connected?'Connected · you can import updates':count+' '+(group.id==='browser'?'profile'+(count>1?'s':''):'local item'+(count>1?'s':''))+' found','tw-journey-found'));
          card.append(button(connected?'Import updates':'Connect',async()=>{const selected=[...selections.querySelectorAll('input:checked')],byId=new Map();for(const input of selected){if(!byId.has(input.dataset.id))byId.set(input.dataset.id,[]);byId.get(input.dataset.id).push(input.dataset.name);}try{const result=await request('onboardingAction',{action:'import',profiles:group.id==='browser'?[...byId.keys()]:[],items:group.id==='browser'?[]:[...byId].map(([id,names])=>({id,names}))});state=await request('onboardingState');render();error.textContent=result.warnings?.join(' ')||'';}catch(failure){state=await request('onboardingState');render();throw failure;}},'secondary'));
        }else if(group.id==='browser'){
          // Sign-ins made in Timewarp's browser are kept in its profile; saved
          // passwords can come from a browser's export file.
          card.append(el('p','Sign in once in Timewarp’s browser and it stays signed in. You can also bring saved passwords from Chrome, Edge, Safari or a password manager.','tw-journey-empty'));
          const status=el('p','','tw-journey-found');
          card.append(button('Import saved passwords',async()=>{try{const result=await request('onboardingAction',{action:'import-passwords'});if(!result?.cancelled)status.textContent='Imported '+result.imported+' sign-in'+(result.imported===1?'':'s')+' into the Vault. Delete the exported file now; it isn’t encrypted.';}catch(failure){status.textContent=failure.message||'The passwords couldn’t be imported.';}},'secondary'),status);
        }else card.append(el('p',group.id==='codex'?'No local setup found. Online ChatGPT memories aren’t stored on this computer.':'No local setup found.','tw-journey-empty'));
        if(group.id==='cursor')card.append(button('Choose a Cursor project',async()=>{detection=await request('onboardingAction',{action:'cursor-folder'});render()},'text'));list.append(card);
      }
      if(detection.errors?.length)error.textContent=detection.errors.join(' ');
    }
    function renderPlans(){const audiences=el('div',null,'tw-audiences');audiences.setAttribute('role','group');audiences.setAttribute('aria-label','Plan type');for(const type of ['individual','enterprise']){const choice=button(type==='individual'?'Individual':'Enterprise',async()=>{planAudience=type;render()},'secondary');choice.setAttribute('aria-pressed',String(planAudience===type));audiences.append(choice);}content.append(audiences);const slot=el('div',null,'tw-journey-plan-grid');content.append(slot);footer('theme');const version=epoch;
      if(state.pendingPlan){slot.classList.add('pending');slot.append(el('h2','Finish your secure checkout'),el('p','Your plan will be selected after the payment service confirms it. Return here when you’re done.'),button('Check payment status',checkPlan,'secondary'),button('Choose another plan',async()=>{await advance('cancel-plan')},'quiet'));schedulePayment();return;}
      slot.append(el('p','Loading plans…','tw-journey-subtitle'));request('cloud',{route:'/billing/service',data:{action:'status'}}).then(data=>{
        if(disposed||version!==epoch)return;if(!Array.isArray(data.plans)||!data.plans.length)throw Error('Plans are temporarily unavailable.');slot.replaceChildren();
        for(const plan of data.plans.filter(plan=>planAudience==='enterprise'?['free','ultra'].includes(plan.id):['free','max'].includes(plan.id))){if(!Number.isFinite(plan.monthlyUsd)||!Number.isFinite(plan.monthlyCredits))throw Error('Plans are temporarily unavailable.');const card=el('article',null,'tw-journey-plan');if(plan.id==='max')card.dataset.recommended='true';card.append(el('div',plan.id==='max'?'A little extra momentum':'Your pace','tw-journey-plan-kicker'),el('h2',plan.name));const price=el('p',null,'tw-journey-price');price.append(el('strong',new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(plan.monthlyUsd)),el('span',' / month'));card.append(price,el('p',plan.id==='free'?'Bring your ChatGPT / Codex subscription, or buy credits.':new Intl.NumberFormat().format(plan.monthlyCredits)+' AI credits every month.','tw-journey-card-copy'),el('p',plan.id==='free'?'Your agent. Your files. Your workspace.':'More room for ambitious work.','tw-journey-card-copy'),button('Choose '+plan.name,()=>advance('select-plan',{plan:plan.id}),plan.id==='max'?'primary':'secondary'));slot.append(card);}content.append(el('p','Prices in USD. Paid plans renew monthly. Payment is completed securely with Stripe.','tw-journey-fineprint'));
      }).catch(failure=>{if(version===epoch){slot.replaceChildren(el('p',failure.message),button('Retry plans',async()=>render(),'secondary'));}});
    }
    function schedulePayment(){clearTimeout(poll);if(!disposed&&state.pendingPlan)poll=setTimeout(()=>void run(checkPlan),5000);}
    async function checkPlan(){const next=await request('onboardingAction',{action:'check-plan'});state=next;if(next.paymentPending){error.textContent='Payment is still awaiting confirmation.';schedulePayment();}else render();}
    const focus=()=>{if(state.pendingPlan&&!busy)void run(checkPlan)};window.addEventListener('focus',focus);
    async function load(){if(disposed)return;try{state=await request('onboardingState');if(state.completed){location.hash='#/';return;}render();}catch(failure){content.replaceChildren(el('h1','Let’s try that again.'),el('p',failure.message),button('Retry setup',load));}}
    content.append(el('p','Getting ready to meet you…','tw-journey-subtitle'));
    if(window.timewarpReadyOrganization)void load();else window.addEventListener('timewarp:organization-ready',load,{once:true});
  };
})();
