"use strict";
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto'), assert = require('node:assert/strict');
const acorn = require('acorn');
const { presets, defaultAccent } = require('../shared/appearance.cjs');
async function verify() {
  const asar = await import('@electron/asar');
  const root = path.resolve(__dirname, '..');
  const mac = process.argv.includes('--mac'), archiveOnly = process.argv.includes('--archive-only');
  if (archiveOnly && !mac) throw new Error('Archive-only verification is reserved for the Mac archive; Windows requires executable integrity checks.');
  const staged = process.argv.includes('--staged') || mac;
  const supplied=process.argv.indexOf('--app-dir');
  const native = mac ? path.join(supplied>=0?path.resolve(process.argv[supplied+1]):path.join(root,'build/mac-preview/mac-arm64/Timewarp Preview.app'),'Contents') : (staged ? path.join(root,'build/native') : path.resolve(root,'../energy-testv1/app'));
  const archive = archiveOnly ? path.join(root,'build/timewarp-mac-app.asar') : path.join(native,mac?'Resources/app.asar':'resources/app.asar');
  const exe = mac ? path.dirname(native) : (staged&&!fs.existsSync(path.join(native,'Timewarp.exe'))?path.join(native,'Timewarp Preview.exe'):path.join(native,'Timewarp.exe'));
  const read = name => asar.extractFile(archive, name.split('/').join(path.sep)).toString('utf8');
  assert.equal(JSON.parse(read('package.json')).productName, 'Timewarp');
  const main = read('out/main/index.js');
  const updaterNode=acorn.parseExpressionAt(main,main.indexOf('class BRe'),{ecmaVersion:'latest'});
  const NativeUpdater=require('node:vm').runInNewContext('('+main.slice(updaterNode.start,updaterNode.end)+')');
  const inherited=new NativeUpdater({isPackaged:true},'0.8.20','https://upstream.invalid',async()=> 'beta',{},{});
  inherited.start();inherited.configure();inherited.useFeed('http://127.0.0.1/desktop');
  assert.equal((await inherited.checkCurrentFeed()).ok,false);assert.equal((await inherited.requestInstall({})).ok,false);
  assert.ok(main.includes('async backend(){return{type:"local",vault:this.local}}'));
  assert.ok(main.includes('sanitizeCard(r,e)'));
  assert.ok(main.includes('.bindNativeAccount(new Jre('));
  assert.ok(main.includes('allowed:false,enabled:false'));
  assert.ok(main.includes('const Tr=async()=>false'));
  assert.ok(main.includes('.attachNativeRuntime({entities:r'));
  assert.ok(!main.includes('revision:"hosted:unavailable"'));
  const boot = read('out/main/bootstrap.js');
  assert.ok(boot.includes('Timewarp Energy') || (staged && boot.includes('Timewarp Preview')));
  assert.ok(boot.includes("require('./timewarp/desktop/runtime.cjs')"));
  assert.ok(boot.includes('requestSingleInstanceLock'));
  assert.throws(()=>read('out/main/timewarp/verify-packaged-auth.cjs'));
  assert.throws(()=>read('out/main/timewarp/verify-local-harness.cjs'));
  assert.throws(()=>read('out/main/timewarp/verify-services.cjs'));
  assert.throws(()=>read('out/main/timewarp/verify-billing-desktop.cjs'));
  assert.throws(()=>read('out/main/timewarp/verify-chatgpt-desktop.cjs'));
  assert.ok(main.includes('.createIntegrations({agents:a.agents'));
  assert.ok(main.includes('.bindToolRuntime({client:r'));
  assert.ok(main.includes('.bindBrowserManager(t)'));
  assert.ok(main.includes('.bindCodexClient(new S9(R))'));
  assert.ok(main.includes('GK=t=>[["model_provider","openai"]'));
  assert.ok(!main.includes('allows_optional_chatgpt_auth`,!0'));
  assert.ok(!main.includes('await f.prepare()'));
  assert.ok(main.includes('.availableModels()'));
  assert.ok(main.includes('accent:' + JSON.stringify(defaultAccent)));
  assert.ok(main.includes('applicationVersion:""'));
  assert.ok(main.includes('texture:{type:"dots",step:0}'));
  for (const token of acorn.tokenizer(main, { ecmaVersion: 'latest', sourceType: 'module' })) {
    if (['string','template'].includes(token.type.label) && typeof token.value === 'string' && !/copyright|licensed under/i.test(token.value)) assert.ok(!/\bEnergy\b/.test(token.value), 'Old display brand remains: ' + token.value.slice(0,80));
  }
  for(const name of ['orbit','nova','cosmo'])assert.ok(asar.extractFile(archive,('out/main/timewarp/assets/mascots/'+name+'.png').split('/').join(path.sep)).length>100000);
  assert.ok(read('out/main/timewarp/desktop/runtime.cjs').includes("require('./updates.cjs').configureUpdates"));
  assert.equal(read('out/main/timewarp/desktop/updates.cjs'),fs.readFileSync(path.join(root,'desktop/updates.cjs'),'utf8'));
  const release = require('../shared/release.cjs').validateRelease(JSON.parse(read('out/main/timewarp/release.json')));
  if(release.enabled){const feed=require('js-yaml').load(fs.readFileSync(path.join(native,'resources/app-update.yml'),'utf8'));assert.equal(feed.url,release.updateUrl);assert.deepEqual(feed.publisherName,release.publisherNames);}
  if(staged&&!release.enabled&&!archiveOnly)assert.ok(!fs.existsSync(path.join(native,mac?'Resources/app-update.yml':'resources/app-update.yml')),'Package never inherits an Energy update feed');
  const config = JSON.parse(read('out/main/timewarp/config.json'));
  const cloudUrl=new URL(config.supabaseUrl);
  assert.equal(cloudUrl.protocol,'https:');assert.ok(!cloudUrl.username&&!cloudUrl.password&&!cloudUrl.search&&!cloudUrl.hash);
  assert.ok(cloudUrl.hostname.endsWith('.supabase.co'),'Configured Timewarp Supabase project');
  assert.ok(config.publishableKey.startsWith('sb_publishable_'));
  assert.deepEqual(config,JSON.parse(fs.readFileSync(path.join(root,'config.json'),'utf8')));
  assert.ok(Object.keys(config).every(key=>['publishableKey','supabaseUrl','googleAuthBridgeUrl'].includes(key)));
  if(config.googleAuthBridgeUrl){const bridge=new URL(config.googleAuthBridgeUrl);assert.equal(bridge.protocol,'https:');assert.ok(!bridge.username&&!bridge.password&&!bridge.search&&!bridge.hash);}
  assert.equal(read('out/main/timewarp/desktop/auth.cjs'),fs.readFileSync(path.join(root,'desktop/auth.cjs'),'utf8'));
  assert.equal(read('out/main/timewarp/shared/google-oauth.cjs'),fs.readFileSync(path.join(root,'shared/google-oauth.cjs'),'utf8'));
  assert.equal(read('out/renderer/timewarp-logo.svg'), fs.readFileSync(path.join(root,'assets/timewarp-logo.svg'), 'utf8'));
  assert.ok(!read('out/renderer/timewarp-logo.svg').includes('<rect'), 'In-app logo has no background tile');
  assert.equal(read('out/renderer/app-icon.svg'), fs.readFileSync(path.join(root, 'assets/app-icon.svg'), 'utf8'));
  assert.equal(read('out/renderer/app-icon.svg'), read('out/renderer/timewarp-logo.svg'), 'Desktop icon keeps the same transparent artwork');
  for (const name of ['app-icon.png', 'app-icon.ico', 'app-icon.icns']) {
    assert.deepEqual(asar.extractFile(archive, ('out/main/timewarp/assets/' + name).split('/').join(path.sep)), fs.readFileSync(path.join(root, 'assets', name)), 'Packaged app icon matches the vector export: ' + name);
  }
  const runtime=read('out/main/timewarp/desktop/runtime.cjs');
  if(staged&&!archiveOnly){const {getCurrentFuseWire,FuseState,FuseV1Options}=await import('@electron/fuses');const fuses=await getCurrentFuseWire(exe);for(const name of ['RunAsNode','EnableNodeOptionsEnvironmentVariable','EnableNodeCliInspectArguments','GrantFileProtocolExtraPrivileges'])assert.equal(fuses[FuseV1Options[name]],FuseState.DISABLE);for(const name of ['EnableCookieEncryption','EnableEmbeddedAsarIntegrityValidation','OnlyLoadAppFromAsar'])assert.equal(fuses[FuseV1Options[name]],FuseState.ENABLE);}
  assert.ok(runtime.includes('config.supabaseUrl}/functions/v1/timewarp-energy'));
  for(const file of asar.listPackage(archive).filter(file=>/[/\\]out[/\\].*\.(?:js|cjs|json)$/.test(file)&&!file.includes('licenses'))){
    assert.ok(!/(?:https?|wss?):\/\/[^\s"'`]*?(?:getenergy\.com|generalwork\.ai|newco-trace-ingest\.computerwork\.workers\.dev)/i.test(read(file.replace(/^[/\\]/,''))),'Upstream server URL in executable code: '+file);
  }
  assert.equal(read('out/main/timewarp/desktop/chatgpt.cjs'),fs.readFileSync(path.join(root,'desktop/chatgpt.cjs'),'utf8'));
  assert.equal(read('out/main/timewarp/desktop/ai-funding.cjs'),fs.readFileSync(path.join(root,'desktop/ai-funding.cjs'),'utf8'));
  assert.equal(read('out/main/timewarp/desktop/codex-funding.cjs'),fs.readFileSync(path.join(root,'desktop/codex-funding.cjs'),'utf8'));
  assert.equal(read('out/renderer/timewarp-billing.js'),fs.readFileSync(path.join(root,'desktop/native-billing.js'),'utf8'));
  assert.equal(read('out/renderer/timewarp-billing.css'),fs.readFileSync(path.join(root,'desktop/billing.css'),'utf8'));
  assert.equal(read('out/renderer/timewarp-controls.css'),fs.readFileSync(path.join(root,'desktop/controls.css'),'utf8'));
  assert.equal(read('out/renderer/timewarp-connector-browser.js'),fs.readFileSync(path.join(root,'desktop/connector-browser.js'),'utf8'));
  assert.ok(!runtime.includes('new BrowserWindow'));
  assert.ok(!runtime.includes('openCloud'));
  assert.throws(()=>read('out/main/timewarp/web/index.html'));
  const html=read('out/renderer/index.html');
  assert.ok(html.includes('<link rel="icon" href="./app-icon.svg">'));
  assert.ok(!html.includes('timewarp-launcher'));
  assert.ok(!html.includes('timewarp-native.js'));
  assert.ok(html.includes('timewarp-auth.js'));
  assert.ok(html.includes('timewarp-auth.css'));
  assert.ok(html.includes('timewarp-controls.css'));
  assert.ok(html.includes('timewarp-billing.js'));
  assert.ok(html.includes('timewarp-billing.css'));
  assert.ok(html.includes('timewarp-connector-browser.js'));
  assert.ok(html.includes('timewarp-appearance.css'));
  assert.ok(read('out/renderer/timewarp-appearance.css').includes('--theme-accent: #B7D6FF'));
  assert.equal(read('out/renderer/timewarp-appearance.css'), fs.readFileSync(path.join(root,'desktop/appearance.css'), 'utf8'));
  assert.ok(read('out/main/timewarp/desktop/runtime.cjs').includes('migrateAppearance(preferences.appearance)'));
  assert.ok(read('out/renderer/timewarp-auth.css').includes('.timewarp-auth-actions'));
  assert.throws(()=>read('out/renderer/timewarp-native.js'));
  const ui = read('out/renderer/assets/'+(mac?require('../mac-upstream-lock.json').rendererUi:'mermaid-GHXKKRXX-YWFhvrpV.js'));
  assert.ok(ui.includes('Quit Timewarp?'));
  assert.ok(ui.includes('Timewarp agent'));
  assert.ok(ui.includes('children:"Add agent"'));
  assert.ok(ui.includes('children:"New Agent"'));
  assert.ok(ui.includes('"aria-label":"Choose mascot"'));
  assert.ok(ui.includes('avatar:r.kind==="mascot"?{type:"native",imageId:r.imageId}'));
  assert.ok(main.includes('.selectedAvatar(e.imageId)'));
  assert.equal(read('out/renderer/timewarp-agents.css'),fs.readFileSync(path.join(root,'desktop/agents.css'),'utf8'));
  assert.ok(html.includes('timewarp-agents.css'));
  assert.ok(html.includes('timewarp-workspace.css'));
  assert.equal(read('out/renderer/timewarp-workspace.css'),fs.readFileSync(path.join(root,'desktop/workspace.css'),'utf8'));
  assert.ok(ui.includes('data-workspace-home'));
  assert.ok(ui.includes('qMn=()=>null'));
  assert.ok(ui.includes('SiteIcon:LDe'));
  assert.ok(ui.includes('workspaceMode`,"browser"'));
  assert.ok(ui.includes('Search or enter a URL'));
  for(const name of ['orbit','nova','cosmo'])assert.deepEqual(asar.extractFile(archive,('out/renderer/assets/timewarp-mascot-'+name+'.png').split('/').join(path.sep)),fs.readFileSync(path.join(root,'assets/mascots',name+'.png')));
  assert.ok(!ui.includes('Quit Energy?'));
  assert.ok(ui.includes('Timewarp color themes'));
  for (const component of ['Pit', 'HCe', 'kcn', 'zoe', 'Scn']) assert.ok(ui.includes(component + '=()=>null'));
  assert.ok(!ui.includes('versionLabel'));
  assert.ok(!ui.includes('Open-source licenses'));
  assert.ok(!ui.includes('Backdrop dots'));
  assert.ok(!ui.includes('title:"Release channel"'));
  assert.ok(!ui.includes('Pick a color, radiance, and backdrop texture'));
  assert.ok(!ui.includes('children:"E"'));
  for (const preset of presets) assert.ok(ui.includes(JSON.stringify(preset)), preset.name);
  const rendererIndex=read('out/renderer/assets/'+(mac?require('../mac-upstream-lock.json').rendererIndex:'index-C6BbfH_v.js'));
  assert.ok(rendererIndex.includes('accent:' + JSON.stringify(defaultAccent)));
  assert.ok(rendererIndex.includes('texture:{type:"dots",step:0}'));
  assert.ok(rendererIndex.includes('u8=()=>"none"'));
  assert.ok(rendererIndex.includes('c8=' + JSON.stringify(presets.map(preset=>preset.hex)) + '.map(x3)'));
  const accountRoutes = ui.match(/a=\(i==="account"\|\|i==="local"&&e\)&&\/(.+?)\/\.test\(r\.path\),o=/);
  assert.ok(accountRoutes, 'Packaged renderer routes account services explicitly');
  const cloudAccountRoute = new RegExp(accountRoutes[1]);
  for(const route of ['product.organizations.update','product.profile.update','product.images.beginUpload','product.usage.energy','product.chatgpt.connection','product.integrations.list'])assert.ok(cloudAccountRoute.test(route),route);
  for(const route of ['product.settings.get','product.settings.update','product.chats.list','product.vault.list','product.files.list','product.integrations.mcps.list'])assert.ok(!cloudAccountRoute.test(route),route);
  assert.ok(ui.includes('qGe=({local:t,children:e,enabled:n})=>n?h.jsx(GGe,'));
  assert.ok(ui.includes('id:"timewarp-auth-view"'));
  assert.ok(!ui.includes('emailInputId:"login-email"'));
  assert.ok(ui.includes('timewarpMountBilling'));
  assert.ok(ui.includes('await window.timewarpOpenConnectorBrowser(y.connectUrl,{onReady:'));
  assert.ok(ui.includes('openAuthorization:async a=>(await window.timewarpOpenConnectorBrowser(a),null)'));
  assert.ok(!ui.includes('openExternal(y.connectUrl)'));
  assert.ok(!ui.includes('window.open(l.authorizationUrl,"_blank"'));
  assert.ok(!ui.includes('window.open(g.authorizationUrl,"_blank"'));
  assert.ok(!ui.includes('timewarpMountMemories'));
  assert.ok(!ui.includes('timewarpMountSavedData'));
  assert.ok(!ui.includes('Saved documents'));
  assert.ok(!ui.includes('children:"Cloud files"'));
  assert.ok(rendererIndex.includes(encodeURIComponent(fs.readFileSync(path.join(root,'assets/timewarp-logo.svg'), 'utf8'))));
  assert.ok(read('out/main/timewarp/desktop/bridge.cjs').includes('/api/funding/current'));
  const bytes = fs.readFileSync(archive);
  const wanted = crypto.createHash('sha256').update(bytes.subarray(16, 16 + bytes.readUInt32LE(12))).digest('hex');
  if(mac){
    if(!archiveOnly){
      const plist=JSON.parse(require('node:child_process').execFileSync('/usr/bin/plutil',['-convert','json','-o','-',path.join(native,'Info.plist')],{encoding:'utf8'}));
      assert.equal(plist.ElectronAsarIntegrity['Resources/app.asar'].hash,wanted,'Signed Mac bundle pins its ASAR header');
      assert.deepEqual(fs.readFileSync(path.join(native,'Resources',plist.CFBundleIconFile)),fs.readFileSync(path.join(root,'assets/app-icon.icns')));
    }
    console.log('Verified Mac application contracts, Timewarp service routing, isolated profile and packaged native bridge'+(archiveOnly?' (archive only).':', ASAR integrity, icon and hardened fuses.'));
    return;
  }
  const binary = fs.readFileSync(exe);
  const icon = fs.readFileSync(path.join(root, 'assets/app-icon.ico'));
  for (let i = 0; i < icon.readUInt16LE(4); i++) {
    const entry = 6 + i * 16, size = icon[entry] || 256;
    const length = icon.readUInt32LE(entry + 8), offset = icon.readUInt32LE(entry + 12);
    assert.ok(binary.includes(icon.subarray(offset, offset + length)), 'Executable contains the updated ' + size + 'px icon');
  }
  const marker = Buffer.from('[{"file":"resources\\\\app.asar","alg":"SHA256","value":"', 'latin1');
  const position = binary.indexOf(marker);
  assert.ok(position >= 0, 'Embedded Electron integrity resource is present');
  assert.equal(binary.subarray(position + marker.length, position + marker.length + 64).toString('latin1'), wanted);
  assert.ok(fs.readFileSync(path.join(root, 'cloud/index.ts'), 'utf8').indexOf('verifyCloud') < 0);
  assert.ok(fs.readFileSync(path.join(root, 'cloud/index.ts'), 'utf8').indexOf('verifyNative') < 0);
  console.log('Verified original local harness and memory, cloud history adapter, no cloud documents UI, account/billing/model bridge and Electron integrity.');
}
verify().catch(error => { console.error(error.message); process.exitCode = 1; });
