"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
const {snapshotOf,createLocalHistory}=require('../desktop/local-history.cjs');
const source=stripTypeScriptTypes(fs.readFileSync(path.join(__dirname,'../cloud/nativeHistory.ts'),'utf8'),{mode:'strip'}).replace(/^import[^\n]*\n/gm,'').replace(/export /g,'');
const context=vm.createContext({assertCloudSafe:require('../shared/privacy.cjs').assertCloudSafe});vm.runInContext(source,context);
const owner='11111111-1111-4111-8111-111111111111',agent='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333',at='2026-10-04T20:00:00Z';
const chat=()=>({conversation:{id,kind:'dm',createdByEntityId:owner,title:'Chat',createdAt:at,updatedAt:at,lastActivityAt:at,modelSettings:{name:'gpt-5.6-sol',reasoningEffort:'low',serviceTier:null}},members:[{entityId:owner,read:true},{entityId:agent}],entries:[{id:'44444444-4444-4444-8444-444444444444',kind:'message',authorId:owner,createdAt:at,parts:[{type:'text',text:'Hello'},{type:'file',path:'C:/private/file.txt'}]},{kind:'tool_call',secret:'local tool details'}]});
function store(value=chat()){return{conversations:{get:()=>value,list:()=>[{conversation:value.conversation}],subscribe(){return()=>{};}},agents:{get:async()=>({id:agent,ownerUserId:owner,displayName:'Timewarp',repositoryPath:'C:/private',instructions:'Local instructions'}),listActiveByOwner:async()=>[{id:agent}]},browserProfiles:{bootstrap:async()=>{}}};}
test('history exports messages without local attachments, tool traces or assistant files',async()=>{const value=await snapshotOf(store(),owner,id);assert.equal(value.entries.length,1);assert.deepEqual(value.entries[0].parts,[{type:'text',text:'Hello'}]);assert.equal(JSON.stringify(value).includes('C:/private'),false);assert.equal(JSON.stringify(value).includes('Local instructions'),false);});
test('history rejects chats belonging to another account and sensitive message content',async()=>{assert.equal(await snapshotOf(store(),agent,id),null);const value=chat();value.entries[0].parts=[{type:'text',text:'4111 1111 1111 1111'}];await assert.rejects(snapshotOf(store(value),owner,id));});
test('server history accepts only known message authors and never saves arbitrary fields',async()=>{const value=await snapshotOf(store(),owner,id);value.localFiles={data:'file content'};const checked=context.historySnapshot(owner,value);assert.equal(checked.localFiles,undefined);assert.throws(()=>context.historySnapshot(agent,value));value.entries[0].authorId='another-account';assert.throws(()=>context.historySnapshot(owner,value));});
test('privacy mode pauses history upload and server failures retry on the next sync',async()=>{let privateMode=true,calls=0,failed=true;const sync=createLocalHistory({store:store(),workspace:{},settings:{get:async()=>({privacy:{mode:privateMode?'private':'standard'}})},userId:()=>owner,cloud:async(_route,input)=>{calls++;if(failed)throw Error('offline');return input.operation==='list'?{chats:[]}:{saved:true};}});try{await sync.sync();assert.equal(calls,0);privateMode=false;await sync.sync();assert.equal(calls,1);failed=false;await sync.sync();assert.equal(calls,3);}finally{sync.stop();}});

test('same-account sync downloads subsequent remote chats, all pages, and applies metadata before append changes local timestamps',async()=>{
  const rows=new Map(),remote=[];let saved=0;
  const local={conversations:{subscribe:()=>()=>{},get:key=>rows.get(key),list:()=>Array.from(rows.values()),create:c=>rows.set(c.id,{conversation:{...c,updatedAt:'2099-01-01T00:00:00Z'},members:c.members.map(m=>({...m,read:true})),entries:[]}),appendEntry:e=>{const row=rows.get(e.conversationId);row.entries.push(e);row.conversation.updatedAt='2099-01-01T00:00:00Z';},setTitle:(key,title)=>{rows.get(key).conversation.title=title;},setModelSettings:(key,value)=>{rows.get(key).conversation.modelSettings=value;},archive:key=>{rows.get(key).members[0].archivedAt=at;},unarchive:key=>{rows.get(key).members[0].archivedAt=null;},setRead:(key,_owner,read)=>{rows.get(key).members[0].read=read;}},agents:{get:async()=>({id:agent,ownerUserId:owner,displayName:'Timewarp'}),listActiveByOwner:async()=>[{id:agent}]},browserProfiles:{bootstrap:async()=>{}}};
  const sync=createLocalHistory({store:local,workspace:{},settings:{get:async()=>({privacy:{mode:'standard'}})},userId:()=>owner,cloud:async(_route,input)=>{if(input.operation==='save'){saved++;return{saved:true};}const offset=input.offset||0;return{chats:remote.slice(offset,offset+100),nextOffset:remote.length>offset+100?offset+100:null};}});
  try{
    await sync.sync();
    for(let i=0;i<101;i++){const value=await snapshotOf(store(),owner,id);value.conversation.id=require('node:crypto').randomUUID();value.conversation.archived=true;value.conversation.read=false;remote.push(value);}
    await sync.sync();assert.equal(rows.size,101);assert.equal(saved,0);assert.ok(Array.from(rows.values()).every(row=>row.members[0].archivedAt&&!row.members[0].read&&row.entries.length===1));
    await sync.sync();assert.equal(saved,0);assert.equal(rows.size,101);
  }finally{sync.stop();}
});
test('first upload saves older messages too, splitting long histories into bounded idempotent batches',async()=>{
  const value=chat();value.entries=Array.from({length:1501},(_,i)=>({...value.entries[0],id:require('node:crypto').randomUUID(),parts:[{type:'text',text:'Message '+i}]}));
  const batches=[],sync=createLocalHistory({store:store(value),workspace:{},settings:{get:async()=>({privacy:{mode:'standard'}})},userId:()=>owner,cloud:async(_route,input)=>{if(input.operation==='list')return{chats:[]};batches.push(input.snapshot.entries);return{saved:true};}});
  try{await sync.sync();assert.deepEqual(batches.map(b=>b.length),[1000,501]);assert.equal(batches[0][0].parts[0].text,'Message 0');await sync.sync();assert.equal(batches.length,2);}finally{sync.stop();}
});
