/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthBridgeRouteImport } from './routes/auth.bridge'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as AuthV1CallbackRouteImport } from './routes/auth.v1.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthV1CallbackRoute = AuthV1CallbackRouteImport.update({
  id: '/auth/v1/callback',
  path: '/auth/v1/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/v1/callback': typeof AuthV1CallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/v1/callback': typeof AuthV1CallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/v1/callback': typeof AuthV1CallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/bridge' | '/auth/google' | '/auth/v1/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/bridge' | '/auth/google' | '/auth/v1/callback'
  id: '__root__' | '/' | '/auth/bridge' | '/auth/google' | '/auth/v1/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  AuthV1CallbackRoute: typeof AuthV1CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/v1/callback': {
      id: '/auth/v1/callback'
      path: '/auth/v1/callback'
      fullPath: '/auth/v1/callback'
      preLoaderRoute: typeof AuthV1CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  AuthV1CallbackRoute: AuthV1CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
